
package br.com.fiap.clientheader;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWeb", targetNamespace = "http://ws.exemplo.fiap.com.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWeb {


    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.clientheader.NovoResponse
     */
    @WebMethod
    @WebResult(name = "novoResponse", targetNamespace = "http://ws.exemplo.fiap.com.br/", partName = "result")
    @Action(input = "http://ws.exemplo.fiap.com.br/AlunoWeb/novoRequest", output = "http://ws.exemplo.fiap.com.br/AlunoWeb/novoResponse")
    public NovoResponse novo(
        @WebParam(name = "novo", targetNamespace = "http://ws.exemplo.fiap.com.br/", partName = "parameters")
        Novo parameters,
        @WebParam(name = "Username", targetNamespace = "http://ws.exemplo.fiap.com.br/", header = true, partName = "Username")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.exemplo.fiap.com.br/", header = true, partName = "Password")
        String password);

    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.clientheader.ListarResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "listarResponse", targetNamespace = "http://ws.exemplo.fiap.com.br/", partName = "result")
    @Action(input = "http://ws.exemplo.fiap.com.br/AlunoWeb/listarRequest", output = "http://ws.exemplo.fiap.com.br/AlunoWeb/listarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.exemplo.fiap.com.br/AlunoWeb/listar/Fault/Exception")
    })
    public ListarResponse listar(
        @WebParam(name = "listar", targetNamespace = "http://ws.exemplo.fiap.com.br/", partName = "parameters")
        Listar parameters,
        @WebParam(name = "Username", targetNamespace = "http://ws.exemplo.fiap.com.br/", header = true, partName = "Username")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.exemplo.fiap.com.br/", header = true, partName = "Password")
        String password)
        throws Exception_Exception
    ;

}
